setup svelte-app
ioxio-dataspace/dataspace-index-page pull request #7
Opened 2023-04-18 20:37 UTC by omarudolley

2023-04-19 10:09 UTC, joakimnordling requested changes
I added some comments. In addition to that, I'd want to highlight one more issue.

When you run `pnpm build` you end up with a `build` folder that contains something like this:
```
.
├── _app
│   ├── immutable
│   │   ├── assets
│   │   │   ├── _layout.2a60cf2f.css
│   │   │   ├── _page.9c3ef556.css
│   │   │   ├── footerLogo.67374396.svg
│   │   │   └── ioxioLogo.93fbc29e.svg
│   │   ├── chunks
│   │   │   ├── 0.18a40fd0.js
│   │   │   ├── 1.64f6f80b.js
│   │   │   ├── 2.b9a50649.js
│   │   │   ├── _layout.da46b06b.js
│   │   │   ├── index.8e4077fa.js
│   │   │   └── singletons.633c20ed.js
│   │   └── entry
│   │       ├── _layout.svelte.7ba16066.js
│   │       ├── _layout.ts.984db11e.js
│   │       ├── _page.svelte.c0f967f8.js
│   │       ├── app.4ffded03.js
│   │       ├── error.svelte.5344bea5.js
│   │       └── start.e5722424.js
│   └── version.json
├── favicon.png
└── index.html
```

If you have a look at the pipeline `.github/workflows/deploy.yaml`, you'll notice that it will only copy over the `index.html` file to the `dist` branch, nothing else. I'm not now sure of the specs, i.e. if we'll want to allow this index page to require a lot of more files. If we do want to allow it to require all these other files, then we'll have to change the pipeline and do changes in the other repos that use the index page. The other solution is to try to ensure only one standalone `index.html` is created at build time. This latter is what has at least earlier been the goal for this project.

2023-04-19 10:09 UTC, joakimnordling commented on package.json
> +  "name": "svelte-app",
How about calling it dataspace-index-page?

2023-04-19 10:09 UTC, joakimnordling commented on src/app.html
> +     <meta charset="utf-8" />
Please fix the indentation.

2023-04-19 10:09 UTC, joakimnordling commented on src/app.html
> +   <link rel="preconnect" href="https://api.fonts.coollabs.io" crossorigin />
Please fix the indentation.

2023-04-19 10:09 UTC, joakimnordling commented on src/routes/+layout.svelte
> +    import Layout from "$components/Layout.svelte"
Please fix the indentation.

2023-04-19 10:09 UTC, joakimnordling commented on src/routes/+page.svelte
> +  }
The indentation looks pretty bad.

2023-04-19 10:09 UTC, joakimnordling commented on static/favicon.png
I don't think we want to use this as a favicon or include it in the final build.

2023-04-19 10:09 UTC, joakimnordling commented on package.json
> -    "start": "craco start",
The README still references `pnpm run start`, so could you update the README as well?

2023-04-20 08:44 UTC, joakimnordling requested changes
Please don't use hardcoded links to the sandbox environment, use the placeholders so the links will point to the correct dataspace.

2023-04-21 13:14 UTC, TheHelias commented
There should be more vertical padding in the header.
Design
![image](https://user-images.githubusercontent.com/32454603/233644932-c02cb2e0-7da1-40ab-be83-e938e1030bda.png)

Implementation
![image](https://user-images.githubusercontent.com/32454603/233644977-6bc02530-1194-4cfc-9f80-05ee405a0587.png)

2023-04-21 13:18 UTC, TheHelias commented
There should be more horizontal padding in the content

Design
![image](https://user-images.githubusercontent.com/32454603/233645748-ba265b21-08cb-4c14-87c0-d86efecce582.png)


Implementation
![image](https://user-images.githubusercontent.com/32454603/233645866-c9e4117b-eb3a-4c17-a14c-2799edfca0db.png)

2023-04-24 13:26 UTC, fbjorn commented on src/components/Footer.svelte
> +  import FooterLogo from "$lib/assets/footerLogo.svg?component"
what this `?component` is required for? I removed it locally and it still works

2023-04-24 13:26 UTC, fbjorn commented on svelte.config.js
> +import { optimizeImports } from "carbon-preprocess-svelte"
we don't use carbon components in this project, probably it's not required

2023-04-24 13:26 UTC, fbjorn commented on src/theme/mixins.scss
> +  // TODO: Decide on breakpoint values. maybe get it from Carbon
since we don't use carbon in this project, probably it's better to remove these TODO comments

2023-04-24 13:26 UTC, fbjorn commented on svelte.config.js
> +import { optimizeImports } from "carbon-preprocess-svelte"
also remove `carbon-preprocess-svelte` from the dependencies

2023-04-24 13:26 UTC, fbjorn commented on src/components/CenterColumn.svelte
> +    height: 100%;
no matter how tall my screen is, I get the vertical scroll bar every time. I checked the props in DevTools and figured out that this `height: 100%` is causing the issue

2023-04-24 14:57 UTC, omarudolley commented on src/components/Footer.svelte
> +  import FooterLogo from "$lib/assets/footerLogo.svg?component"
typescript check fails. try running` pnpm check`

2023-04-24 15:05 UTC, omarudolley commented on src/components/CenterColumn.svelte
> +    height: 100%;
I removed it

2023-04-27 09:28 UTC, fbjorn approved these changes

2023-04-27 10:58 UTC, joakimnordling commented on .github/workflows/deploy.yaml
> +      - svelte-implementation
This needs to be reverted before merging.

2023-04-28 11:05 UTC, joakimnordling approved these changes

2023-04-28 11:33 UTC, merged